### ISSUE TITLE
Crud Functionality For Games.

### ISSUE THREAD

**Issue by DPJProgramming** [DPJProgramming/week-3-basic-Ecommerce#5]
- [ ] Set up model for games
- [ ] Create Database and table for games
- [ ] Add Create page for games
- [ ] Add Select page (game catalog)
- [ ] Add Update page for games
- [ ] Add Delete page for games
